In [ ]:
# @title
import sys
import io
import time
import numpy as np

In [ ]:
t = []
t1 = time.time()
def GetReverse(literal):
    if literal[0] == '~':
      return literal[1:]
    else:
        return '~' + literal

def is_satisfiable(n_vars, clauses):
    candidates = {frozenset()}

    for clause in clauses:
        temp = set()

        for s in candidates:
            for literal in clause:

                if GetReverse(literal) not in s:

                    temp.add(s | {literal})

        candidates = temp

        if len(candidates) == 0:
            return False

    return True


def load_case(f):
    n_vars, n_clauses = f.readline().split()
    clauses = [f.readline().strip().split(' v ') for _ in range(int(n_clauses))]
    return int(n_vars), clauses


t2 = time.time()
t.append(float(t2-t1))
def main(f=sys.stdin):
    num_cases = int(f.readline())
    n=0
    for i in range(num_cases):
        n_vars, clauses = load_case(f)
        print(clauses)
        n = n_vars
        result = is_satisfiable(n_vars, clauses)

        print(f"{'satisfiable' if result else 'unsatisfiable'}")
        print(f"Execution time: {sum(t)} seconds")
    return clauses, n

In [ ]:
data = """
1
3 5
X1 v X2 v X3
X1 v ~X2
X2 v ~X3
X3 v ~X1
~X1 v ~X2 v ~X3
""".strip()

In [ ]:
clauses,n  = main(io.StringIO(data))

[['X1', 'X2', 'X3'], ['X1', '~X2'], ['X2', '~X3'], ['X3', '~X1'], ['~X1', '~X2', '~X3']]
unsatisfiable
Execution time: 0.0008966922760009766 seconds


In [ ]:
num=n
exps=[]
exp = [-1]*(num+1)
for clause in clauses:
  exp = [-1]*(num+1)
  print(clause)
  for item in clause:
    print(item, item[-1], item[0])
    if item[0]=='~':
      exp[int(item[-1])]=0
    else:
      exp[int(item[-1])]=1
  exp = exp[1:]
  print(exp)
  exps.append(exp)

['X1', 'X2', 'X3']
X1 1 X
X2 2 X
X3 3 X
[1, 1, 1]
['X1', '~X2']
X1 1 X
~X2 2 ~
[1, 0, -1]
['X2', '~X3']
X2 2 X
~X3 3 ~
[-1, 1, 0]
['X3', '~X1']
X3 3 X
~X1 1 ~
[0, -1, 1]
['~X1', '~X2', '~X3']
~X1 1 ~
~X2 2 ~
~X3 3 ~
[0, 0, 0]


In [ ]:
exps

[[1, 1, 1], [1, 0, -1], [-1, 1, 0], [0, -1, 1], [0, 0, 0]]

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
clauses

[['X1', 'X2', 'X3'],
 ['X1', '~X2'],
 ['X2', '~X3'],
 ['X3', '~X1'],
 ['~X1', '~X2', '~X3']]

In [ ]:
list1 = []
max1 = 1
for clause in clauses:
  if max1<len(clause):
    max1 = len(clause)
    #print(max1)

#print(max1)
for clause in clauses:
  #print(clause)
  L1 = [0]*(max1+1)
  #print(L1)
  for item in clause:
    #print(item, len(item))
    if len(item)>2:
      if item[0] == "~":
        #print(item[0], item[1], item[2])
        L1[int(item[2])] =-1
        #print(L1)
    else:
      L1[int(item[1])]  =1
    #print(L1)
  #print(L1[1:])
  list1.append((L1[1:]))


In [ ]:
list1

[[1, 1, 1], [1, -1, 0], [0, 1, -1], [-1, 0, 1], [-1, -1, -1]]

In [ ]:
pop_size = 10
init_population = np.array([0]*max1)
for i in range(pop_size):
  chr1 = np.random.randint(0, 2, max1)
  init_population = np.vstack((init_population, chr1))
init_population = init_population[1:, :]
print(init_population)

[[1 1 0]
 [0 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [0 1 0]
 [0 1 0]]


In [ ]:
init_pop_bool=[]
for i in init_population:
  L1 =[True if j==1 else False for j in i]
  init_pop_bool.append(L1)

In [ ]:
 init_pop_bool

[[True, True, False],
 [False, True, False],
 [True, True, True],
 [True, False, False],
 [False, True, True],
 [True, True, True],
 [False, False, True],
 [False, False, False],
 [False, True, False],
 [False, True, False]]

In [ ]:
chr = init_population[0]
k=0
for exp1 in exps:
  for i in chr:
    result = [i*x for x in exp1 if x != -1]
    if 1 in result:
      print(result, k)
    k+=1
  print(exp1)

[1, 1, 1] 0
[1, 1, 1] 1
[1, 1, 1]
[1, 0] 3
[1, 0] 4
[1, 0, -1]
[1, 0] 6
[1, 0] 7
[-1, 1, 0]
[0, 1] 9
[0, 1] 10
[0, -1, 1]
[0, 0, 0]


In [ ]:
for chr in init_pop_bool:
  print(chr)
  chr

[True, True, False]
[False, True, False]
[True, True, True]
[True, False, False]
[False, True, True]
[True, True, True]
[False, False, True]
[False, False, False]
[False, True, False]
[False, True, False]


In [ ]:
chromosome = [1, 1, 1]

output = []
for clause in exps:
    clause_result = 0
    for i in range(len(clause)):
        if clause[i] == 1 and chromosome[i] == 1:
            clause_result = 1
            break
    output.append(clause_result)

print(output)


[1, 1, 1, 1, 0]


In [ ]:
output

[1, 1, 1, 1, 0]

In [ ]:
cnt = 0
for i in range(len(output)):
 if output[i] == 1:
    cnt += 1
print(cnt)

4


In [ ]:
if cnt == len(clauses):
  print("satisfiable")
else:
  print("unsatisfiable")

unsatisfiable
